# Generated by Django 5.2.10 on 2026-01-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistModule', '0002_remove_wishlist_user_wishlist_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Customer',
            new_name='customer',
        ),
    ]
