# Generated by Django 5.2.10 on 2026-01-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_image'),
        ('wishlistModule', '0004_alter_wishlistitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product'),
        ),
    ]
